### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by rmosolgo** [prawnpdf/pdf-core#57]
Hi! I came source diving to investigate the performance of the `real(number)` method, but I found it was already greatly improved in 236fbf61ae09163384d4d934c3220344576f8c28. For now, I've forked the repo and I'm bundling from github, but how about releasing a new version with those improvements? Thanks :bow: !

**Comment by gettalong** [comment]
Please see https://github.com/prawnpdf/prawn/issues/1195#issuecomment-1125418754

**Comment by rmosolgo** [comment]
Oh -- I see it's quite a process. Well, I'll keep bundling from github for now, thanks!
